package com.lexienglish.service;

import com.lexienglish.entity.*;
import com.lexienglish.repository.DocumentRepository;
import com.lexienglish.repository.ExerciseRepository;
import com.lexienglish.repository.FlashcardRepository;
import com.lexienglish.repository.LessonRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;

/**
 * Mock implementation of DocumentParsingService for development.
 * Generates sample lessons, flashcards, and exercises.
 * Replace with AI-based implementation for production.
 */
@Slf4j
@Service
@Primary
@RequiredArgsConstructor
public class MockDocumentParsingService implements DocumentParsingService {

    private final DocumentRepository documentRepository;
    private final LessonRepository lessonRepository;
    private final FlashcardRepository flashcardRepository;
    private final ExerciseRepository exerciseRepository;
    private final FileStorageService fileStorageService;

    @Override
    @Transactional
    public void parseDocument(Long documentId) {
        log.info("Starting mock parsing for document: {}", documentId);

        Document document = documentRepository.findById(documentId)
                .orElseThrow(() -> new RuntimeException("Document not found: " + documentId));

        try {
            // Update status to processing
            document.setStatus(Document.ProcessingStatus.PROCESSING);
            documentRepository.save(document);

            // Read file content (for TXT files)
            String content = "";
            if (document.getFileType() == Document.FileType.TXT) {
                content = fileStorageService.readFileContent(document.getFilePath());
                document.setRawContent(content);
            }

            // Generate mock lessons
            List<Lesson> lessons = generateMockLessons(document);
            lessonRepository.saveAll(lessons);

            // Generate mock flashcards
            List<Flashcard> flashcards = generateMockFlashcards(document);
            flashcardRepository.saveAll(flashcards);

            // Update document
            document.setTotalLessons(lessons.size());
            document.setStatus(Document.ProcessingStatus.COMPLETED);
            documentRepository.save(document);

            log.info("Mock parsing completed for document: {}. Lessons: {}, Flashcards: {}",
                    documentId, lessons.size(), flashcards.size());

        } catch (Exception e) {
            log.error("Mock parsing failed for document: {}", documentId, e);
            document.setStatus(Document.ProcessingStatus.FAILED);
            documentRepository.save(document);
        }
    }

    private List<Lesson> generateMockLessons(Document document) {
        List<Lesson> lessons = new ArrayList<>();

        String[] chapterTitles = {
                "Introduction and Key Concepts",
                "Vocabulary Building",
                "Grammar Essentials",
                "Reading Comprehension",
                "Practice Exercises"
        };

        for (int i = 0; i < chapterTitles.length; i++) {
            Lesson lesson = Lesson.builder()
                    .title(chapterTitles[i])
                    .summary("This chapter covers " + chapterTitles[i].toLowerCase()
                            + " based on the uploaded document.")
                    .content("# " + chapterTitles[i]
                            + "\n\nThis is sample content for the lesson. In production, this would be generated by AI analysis of the document content.\n\n## Key Points\n\n1. First important concept\n2. Second important concept\n3. Third important concept")
                    .orderIndex(i)
                    .document(document)
                    .difficultyLevel(Lesson.DifficultyLevel.B1)
                    .build();

            lessons.add(lesson);

            // Add exercises to each lesson
            List<Exercise> exercises = generateMockExercises(lesson);
            lesson.setExercises(exercises);
        }

        return lessons;
    }

    private List<Exercise> generateMockExercises(Lesson lesson) {
        List<Exercise> exercises = new ArrayList<>();

        // Multiple choice question
        Exercise mcq = Exercise.builder()
                .question("What is the main topic discussed in this chapter?")
                .exerciseType(Exercise.ExerciseType.MULTIPLE_CHOICE)
                .correctAnswer("The key concepts of " + lesson.getTitle().toLowerCase())
                .options(List.of(
                        "The key concepts of " + lesson.getTitle().toLowerCase(),
                        "An unrelated topic",
                        "Historical events",
                        "None of the above"))
                .explanation("This chapter focuses on " + lesson.getTitle())
                .lesson(lesson)
                .orderIndex(0)
                .build();
        exercises.add(mcq);

        // Fill in the blank
        Exercise fillBlank = Exercise.builder()
                .question("Complete the sentence: The most important aspect of learning is _____.")
                .exerciseType(Exercise.ExerciseType.FILL_IN_THE_BLANK)
                .correctAnswer("practice")
                .explanation("Regular practice is essential for language learning.")
                .lesson(lesson)
                .orderIndex(1)
                .build();
        exercises.add(fillBlank);

        // True/False
        Exercise trueFalse = Exercise.builder()
                .question("This lesson covers advanced topics only.")
                .exerciseType(Exercise.ExerciseType.TRUE_FALSE)
                .correctAnswer("FALSE")
                .options(List.of("TRUE", "FALSE"))
                .explanation("The lesson is designed for intermediate level (B1).")
                .lesson(lesson)
                .orderIndex(2)
                .build();
        exercises.add(trueFalse);

        return exercises;
    }

    private List<Flashcard> generateMockFlashcards(Document document) {
        List<Flashcard> flashcards = new ArrayList<>();

        String[][] vocabPairs = {
                { "Comprehensive", "Including all or nearly all elements; thorough",
                        "The report provides a comprehensive analysis." },
                { "Personalized", "Designed for a particular person",
                        "The platform offers personalized learning paths." },
                { "Adaptive", "Able to adjust to different conditions",
                        "Adaptive learning adjusts to your skill level." },
                { "Proficiency", "A high degree of skill; expertise", "She demonstrated proficiency in English." },
                { "Enhancement", "The action of improving quality or value",
                        "Technology enables enhancement of learning." }
        };

        for (String[] vocab : vocabPairs) {
            Flashcard card = Flashcard.builder()
                    .front(vocab[0])
                    .back(vocab[1])
                    .example(vocab[2])
                    .cardType(Flashcard.CardType.VOCABULARY)
                    .document(document)
                    .user(document.getUser())
                    .build();
            flashcards.add(card);
        }

        return flashcards;
    }
}
